// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsqztictdjcguzchlcdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzcXp0aWN0ZGpjZ3V6Y2hsY2RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NDkzMDMsImV4cCI6MjA2NDUyNTMwM30.lAoqflkxI7scLvvKqtcEj5H23RCxqXQZj4YsgaN14ZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);